- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
@justin808 @robwise Hey guys, I added contributing guide. Can you review it when you'll have time?
> Add contributing guide

- examples/basic/package.json
- examples/css-modules/package.json
- src/bootstrap.loader.js
> Load babel polyfill only for legacy node

- README.md
> Added a section about using Bootswatch themes

- src/bootstrap.styles.loader.js
- src/utils/processModules.js
Solves https://github.com/shakacode/bootstrap-loader/issues/26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/27)
> Load mixins before pre-customizations

- README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/34)
> TYPO: "the a" -> "a"

- examples/basic/package.json
- examples/css-modules/package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/46)
> removed relative bootstrap-loader paths from example package.json files

- examples/basic/package.json
- examples/css-modules/package.json
Small cleanup changes to the package.json files in /examples
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/57)
> Cleanup example package.json files

- README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/64)
> Delete duplicate paragraph

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/99)
> Fix terminology with Webpack entry points

- package.json
Fixes https://github.com/shakacode/bootstrap-loader/issues/118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/119)
> Bump Webpack Minor Version to 1 from 0

- .eslintrc
- package.json
- src/bootstrap.loader.js
- src/bootstrap.scripts.loader.js
- src/bootstrap.styles.loader.js
- src/utils/buildExtractStylesLoader.js
- src/utils/checkBootstrapVersion.js
- src/utils/getEnvProp.js
- src/utils/joinLoaders.js
- src/utils/processStyleLoaders.js
Port https://github.com/shakacode/bootstrap-loader/pull/139 to v1
Needs review only an additional commit [Fix linting issues in v1](https://github.com/shakacode/bootstrap-loader/pull/140/commits/f1b9958e9c940cfa26bf091cffedb96e892c139e)
--
I've checked it:
```
cd examples/basic
rm -rf node_modules
npm i
npm run install-local
npm run bs3
```
All is green.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/140)
> Port #139 to v1

- CHANGELOG.md
- CONTRIBUTING.md
- node_package/tests/configCreation.test.js
- src/bootstrap.config.js
- src/bootstrap.loader.js
- src/utils/buildExtractStylesLoader.js
- src/utils/processStyleLoaders.js
* Improve error messages
* fixed failing test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/149)
> Updated CHANGELOG, CONTRIBUTING

- loader.js
- package.json
- src/bootstrap.loader.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/157)
> module.exports all the way to root require

- examples/css-modules/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/165)
> Note about no-config for css-modules example

- CHANGELOG.md
- loader.js
- src/bootstrap.loader.js
See https://github.com/shakacode/bootstrap-loader/pull/98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/162)
> specific exports

- CHANGELOG.md
- node_package/tests/bootstrap.config.test.js
- node_package/tests/utils/buildExtractStylesLoader.test.js
- src/bootstrap.config.js
- src/utils/buildExtractStylesLoader.js
These were the two modifications to production code @justin808 mentioned while reviewing #169. Wanted to make a PR for them before I forgot. This PR is incomplete. Once #169 is merged, I will add/modify unit tests for these changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/177)
> Misc Improvements

- CHANGELOG.md
- README.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/187)
> Release 1.2.1

- CHANGELOG.md
- README.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/188)
> Release 2.0.0-beta.12

- examples/basic/package.json
- examples/css-modules/package.json
- examples/multiple-entries/package.json
- examples/multiple-entries/server.prod.js
- examples/multiple-entries/webpack.dev.config.js
- examples/multiple-entries/webpack.prod.config.js
- node_package/tests/bootstrap.config.test.js
- package.json
fixed lint issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/198)
> Merge pr 194 into master

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/208)
> Fix npm install typo in Readme

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/237)
> Support Webpack2 RCs

- package.json
- src/bootstrap.loader.js
- src/bootstrap.scripts.loader.js
- src/bootstrap.styles.loader.js
fix deprecated warning
link: webpack/loader-utils#56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/269)
> fix deprecated warning

- package.json
Closes #267
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/270)
> Move lint dependencies to dev dependencies.

- src/bootstrap.loader.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/271)
> fixed lint

- README.md
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/290)
> Update README.md for Webpack v2

- .bootstraprc-4-default
- CHANGELOG.md
- README.md
- examples/basic/.bootstraprc-4-example
- examples/basic/package.json
- examples/css-modules/.bootstraprc-4-example
- examples/css-modules/package.json
- examples/multiple-entries/bs4.yml
- examples/multiple-entries/package.json
- package.json
- renamed 'animation' to 'transitions' and 'tags' to 'badge' (fixes #292)
- ordered default properties alphabetically
- updated example configs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/293)
> Update default bootstraprc-4 properties to reflect changes in bootstrap v4 alpha 6

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/304)
> Fix Markdown syntax mixup in README

- README.md
This PR adds docs to address #305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/310)
> Update docs with multiple CSS themes instructions

- examples/basic/webpack.bootstrap.config.js
correcting typo './.boostraprc file in the root'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/327)
> typo in console.log message

- CONTRIBUTING.md
- examples/basic/README.md
- examples/basic/app/markup/bootstrap-dev.html
- examples/basic/package.json
- examples/css-modules/README.md
- examples/css-modules/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/361)
> Update docs, switched npm to yarn

- package.json
Update to fix https://nodesecurity.io/advisories/813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/366)
> update js-yaml to fix vulnerability

- package.json
https://publint.dev/bootstrap-loader@4.0.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/416)
> Fix package warnings

- README.md
Fix broken link
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/422)
> Fix broken link to Bootstrap 3 & 4

- CHANGELOG.md
- package.json
- yarn.lock
Resolves https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/425)
> chore(deps): update semver to v5.7.2

- CHANGELOG.md
- package.json
Helps to quickly develop on this project when using Node's new [corepack](https://nodejs.org/api/corepack.html) functionality.
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/426)
> chore(package): specify manager
