- .bootstraprc-4-default
This was missing from example config file which made backgrounds not working.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/28)
> fixed bootstrap 4 example to include background. #8

- src/bootstrap.loader.js
I think this patch will actually fix #16. Just explain again in the following
for the users who wrote webpack with es6 and there are two way to run
first is using ```babel-node```, second is ```node --harmony``` and add ```require('babel/register');``` at entry point. For these both condition, it will load ```babel/polyfill``` at first in runtime, so we need add a flag to avoid ```bootstrap-loader``` to load ```babel/polyfill``` again.
So I thinks this patch can fix ```ERROR in only one instance of babel-polyfill is allowed``` issue correctly.
btw, I think I can make the code more clean in the beginning of ```src/bootstrap.loader.js```, if I have free time, I will do another PR
Thanks
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> Avoid multiple babel-polyfill loaded

- README.md
You need to use use [\/\\] instead of \/ to match folder separators on Windows.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/44)
> Update README.md to support Windows

- src/bootstrap.loader.js
Untested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/72)
> fixes polyfill require for node < v4.0.0

- .gitignore
- README.md
- examples/basic/package.json
- examples/css-modules/package.json
- package.json
`bootstrap-loader` breaks when `extract-text-webpack-plugin` `2.0.0-beta.0` or higher is used. By adding  `extract-text-webpack-plugin` as a peer dependency with the supported version we can warn to user about this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/109)
> Adding extract text plugin as a peer dependency

- src/bootstrap.config.js
- src/bootstrap.loader.js
- src/utils/logger.js
- src/utils/resolveDefaultConfigPath.js
Instead of #121
Resolves #120
--
```js
export function createConfig({
extractStyles,
configFilePath = defaultUserConfigPath, // <== This was the main point of the pain
}) {
```
The rest is just consequences of removing the technical debt (part of it).
I've moved to the beginning the `default config path` handling in `createConfig()`
with the guard check
```js
if (!configFilePath) {
logger.debug('Using default bootstrap 3 configuration');
```
and the rest of `createConfig()` is the old `user provided config path` handling.
--
`petty` => `pretty`
--
And I've moved the constant
```js
const CONFIG_FILE = '.bootstraprc';
```
to the place it belongs to. `resolveDefaultConfigPath()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix debug messages logging

- CHANGELOG.md
- src/bootstrap.config.js
Logic was mixed up for a default config versus the default location of
the .bootstraprc file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/154)
> Logic for default config, versus custom config

- .bootstraprc-4-default
- examples/basic/.bootstraprc-4-example
- examples/basic/package.json
- examples/css-modules/.bootstraprc-4-example
- examples/css-modules/package.json
- src/utils/createBootstrapRequire.js
- `label` component renamed to `tag` (https://github.com/twbs/bootstrap/pull/19157)
- `pager` component dropped (https://github.com/twbs/bootstrap/pull/18782)
- `utilities-*` now reside in the `utilities` folder
- Scripts now reside in the `js/dist` folder instead of `dist/js/umd`
- To avoid the added complexity of loading styles in sub-folders I've removed `utilities-*` options. We can discuss a good way to implement this if it's needed.
Passes the test~~s~~ and the examples work fine. Theoretically fixes #117.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/167)
> Add bootstrap@4.0.0.alpha.4 compatibility

- node_package/tests/utils/processStyleLoaders.test.js
- src/bootstrap.config.js
- src/bootstrap.loader.js
- src/utils/processStyleLoaders.js
Addresses #52 and #53. I went with the disable opts being undefined by default so the disabling only takes place if someone actually adds the variables to their config.
This PR is incomplete atm. Once #169 gets merged, I'll update this branch by adding the proper unit tests.
Also, do we want to add something about this to the README?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/176)
> Make injection of resolve-url & sass sourcemap optional

- examples/basic/package.json
- examples/basic/server.dev.js
- examples/basic/server.prod.js
- examples/basic/webpack.dev.config.js
- examples/basic/webpack.prod.config.js
- examples/css-modules/package.json
- examples/css-modules/server.dev.js
- examples/css-modules/server.prod.js
- examples/css-modules/webpack.dev.config.js
- examples/css-modules/webpack.prod.config.js
This PR enables the examples to build without errors. I'm not confident that my inclusion of LoaderOptionsPlugin was correct since I don't know exactly how to tell if autoprefixer is working as desired, but at least there are no build errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/180)
> updated example configs

- CHANGELOG.md
- README.md
- examples/basic/.bootstraprc-3-example
- examples/basic/.bootstraprc-4-example
- examples/basic/package.json
- examples/basic/webpack.dev.config.js
- examples/basic/webpack.prod.config.js
- examples/css-modules/.bootstraprc-3-example
- examples/css-modules/.bootstraprc-4-example
- examples/css-modules/package.json
- examples/css-modules/webpack.dev.config.js
- examples/css-modules/webpack.prod.config.js
- examples/multiple-entries/bs3.yml
- examples/multiple-entries/bs4.yml
- examples/multiple-entries/package.json
- examples/multiple-entries/webpack.dev.config.js
- examples/multiple-entries/webpack.prod.config.js
- node_package/tests/utils/buildExtractStylesLoader.test.js
- node_package/tests/utils/processStyleLoaders.test.js
- package.json
- src/utils/buildExtractStylesLoader.js
- src/utils/processStyleLoaders.js
Summary:
-----
The latest build of Webpack (v2.1.0-beta.26) requires loaders be explicitly stated with the `-loader` suffix, thus causing bootstrap-loader to no longer be compatible due to use of shorthand loader names. 
This PR fixes #201. 
Fix Proposed:
-----
This PR handles both cases, with or without `-loader`, to keep compatibility with old webpack users that omit the `-loader` suffix. To do so, I'm proposing the following changes:
Test Plan:
----
`buildExtractStylesLoader.test.js` and `processStyleLoaders.test.js` have both been updated to reflect these new changes and test correctly for the new `-loader` suffix. This should pass the requirement in Webpack v2.1.0-beta.26. 
Some additional configuration work will be required to bring the examples up to par with beta.26, however to …
> Fix #201: Enforce -loader suffix when processing loaders to handle old & new Webpack compatibility

- README.md
Summary:
This PR adds `postcss` to the list of style loader types automatically ensured a `-loader` suffix in the README. 
Simple update to the README on top of #205 to add this missing note, since `postcss` support was added to the `ensureLoadersSuffix` function later on after I had run through the README initially.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/209)
> Add postcss to webpack -loader suffix note in README

- node_package/tests/utils/createUserImport.test.js
- src/utils/createUserImport.js
webpack expects an absolute path.
Fixes #211 .
I updated the relevant test as well and `npm run test` succeeds, are there any other issues?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/212)
> createUserImport should pass an absolute path to webpack.addDependency

- CHANGELOG.md
- README.md
- package.json
- src/bootstrap.config.js
```
"env": {
"development": {
"styleLoaders": ["style-loader", "css-loader", "resolve-url-loader", "sass-loader"],
"extractStyles": false
},
"production": {
"styleLoaders": ["style-loader", "css-loader", "sass-loader"],
"extractStyles": true
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/222)
> Allow styleLoaders to depends to env

- examples/basic/package.json
- examples/basic/server.dev.js
- examples/basic/server.prod.js
- examples/basic/webpack.dev.config.js
- examples/basic/webpack.prod.config.js
- examples/basic/yarn.lock
- examples/css-modules/app/components/GlyphIcons/GlyphIcons.jsx
- examples/css-modules/app/components/Jumbotron/Jumbotron.jsx
- examples/css-modules/app/postcss.config.js
- examples/css-modules/app/startup/App.jsx
- examples/css-modules/package.json
- examples/css-modules/server.dev.js
- examples/css-modules/server.prod.js
- examples/css-modules/webpack.dev.config.js
- examples/css-modules/webpack.prod.config.js
- examples/css-modules/yarn.lock
- examples/multiple-entries/package.json
- examples/multiple-entries/server.dev.js
- examples/multiple-entries/server.prod.js
- examples/multiple-entries/webpack.dev.config.js
- examples/multiple-entries/webpack.prod.config.js
- examples/multiple-entries/yarn.lock
Should be good to go. `resolve-url-loader` upgraded to `^2.0.0` and examples running and linted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/261)
> Update Example Dependencies

- examples/basic/.bootstraprc-3-example
- Fix the spelling of `bootstrap` in .bootstraprc file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/289)
> Fix typo in .bootstraprc-3-example

- .bootstraprc-4-default
- CHANGELOG.md
- README.md
- examples/basic/.bootstraprc-4-example
- examples/basic/app/styles/app.scss
- examples/basic/app/styles/bootstrap/customizations-bs4.scss
- examples/basic/package.json
- examples/basic/yarn.lock
- examples/css-modules/.bootstraprc-4-example
- examples/css-modules/app/assets/styles/bootstrap/customizations-bs4.scss
- examples/css-modules/package.json
- examples/css-modules/yarn.lock
- examples/multiple-entries/app/styles/bootstrap/customizations-bs4.scss
- examples/multiple-entries/bs4.yml
- examples/multiple-entries/package.json
- examples/multiple-entries/yarn.lock
- node_package/tests/bootstrap.config.test.js
- node_package/tests/test_configs/test_bootstraprc
- node_package/tests/test_configs/test_bootstraprc_noversion
- node_package/tests/test_configs/test_bootstraprc_wrongversion
- src/bootstrap.config.js
- src/bootstrap.styles.loader.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/316)
> Added support Bootstrap 4 Beta

- README.md
Fixed 'boostrap' misspelling to two locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/326)
> Simple spelling error fix - boostrap to bootstrap

- README.md
Console will show "Popover variable not defined" error and Popover.js functionality built in to Bootstrap 4 did not work without first adding this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/336)
> add config for Popper for jquery plugin using Bootstrap 4 

- README.md
- node_package/tests/utils/getEnvProp.test.js
- src/utils/getEnvProp.js
If the NODE_ENV specific value for a setting is not found, then a
non-env specific value is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/356)
> Allow ENV specific values to have a default

- examples/basic/.bootstraprc-3-example
- examples/basic/.bootstraprc-4-example
- examples/basic/README.md
- examples/basic/app/markup/bootstrap-dev.html
- examples/basic/app/markup/bootstrap-prod.html
- examples/basic/app/styles/bootstrap/pre-customizations.scss
- examples/basic/app/styles/resources.scss
- examples/basic/package.json
- examples/basic/yarn.lock
- examples/css-modules/README.md
- examples/css-modules/package.json
- examples/css-modules/yarn.lock
- node_package/tests/utils/processStyleLoaders.test.js
- src/utils/processStyleLoaders.js
- yarn.lock
Fixes an issue discovered by author in #285 after upgrading `boostrap-loader`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/357)
> Make it up with sass-resources-loader

- package.json
- yarn.lock
fixes #364 
this updates js-yaml to get past https://nodesecurity.io/advisories/788 as well as some other old packages that folks probably don't want dragged into their project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/365)
> upgrade dependencies 

- CHANGELOG.md
- node_package/tests/utils/processStyleLoaders.test.js
- package.json
- src/bootstrap.scripts.loader.js
- src/bootstrap.styles.loader.js
- src/utils/getFontsPath.js
- src/utils/processStyleLoaders.js
Same as #400 without the `lib` directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/401)
> Minimal changes necessary for Webpack 5 compatibility

- package.json
- yarn.lock
Fixes https://github.com/advisories/GHSA-76p3-8jx3-jpfq with CVSS `9.8 / 10`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/410)
> chore(deps): update loader-utils to v1.4.1

- .eslintrc
According to [official documentation](https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-parser-options), we should change the syntax of configuring `ecmaFeatures`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/415)
> Fix ecmaFeatures deprecation

- CHANGELOG.md
- package.json
- yarn.lock
Fix 239 vulnerabilities.
Among these vulnerabilities, `loader-utils` is a dependency (not a dev dependency) and affects other projects (including react-webpack-rails-tutorial project).
We need a patch release for this ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/418)
> Fix js vulnerabilities

- CHANGELOG.md
- package.json
This PR reverts the bug introduced in #416. Having `type` entry in `package.json` file causes malfunctions in this package.
We need to have a test to cover such situation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/bootstrap-loader/419)
> Remove type entry in package.json
